# Páginas para programar python

1. www.mybinder.org
2. www.kaggle.com
3. www.jupyter.org/try
4. `github jobish` https://mybinder.org/v2/gh/jobish03/jobish03-Visualizacion_de_datos_para_la_toma_de_decisiones/main?filepath=welcome_binder.ipynb

Los paquetes hay que incluir en el archivo `requirements.txt`

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('datasets/antropometria-dataset.csv')
df.head()

,folio,intp,entidad,desc_ent,sexo,edad,meses,peso,ropa,talla,...,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,210295,2,21,PUEBLA,2,38,8,73.70,2,146.4,...,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,101655,3,10,DURANGO,2,11,11,35.65,2,145.1,...,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,10287,6,1,AGUASCALIENTES,2,18,8,54.80,1,162.0,...,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,91526,4,9,DISTRITO FEDERAL,1,10,8,33.40,2,146.5,...,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,210939,3,21,PUEBLA,2,19,3,97.95,2,161.0,...,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215

In [16]:
pip install statsmodels

Requirement already satisfied: statsmodels in /srv/conda/envs/notebook/lib/python3.7/site-packages (0.13.1)
Requirement already satisfied: patsy>=0.5.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (0.5.2)
Requirement already satisfied: pandas>=0.25 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.0.4)
Requirement already satisfied: scipy>=1.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.4.1)
Requirement already satisfied: numpy>=1.17 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.18.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2020.1)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
     |████████████████████████████████| 292 kB 4.7 MB/s
Requirement already satisfied: pandas>=0.23 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.0.4)
Requirement already satisfied: matplotlib>=2.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (3.2.1)
Requirement already satisfied: numpy>=1.15 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.18.5)
Requirement already satisfied: scipy>=1.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from seaborn) (1.4.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.23->seaborn) (2020.1)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.16.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.11.2
Note: you may need to restart the kernel to use updated packages.

In [18]:
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import numpy as np

In [19]:
pip install sklearn

Requirement already satisfied: sklearn in /srv/conda/envs/notebook/lib/python3.7/site-packages (0.0)
Requirement already satisfied: scikit-learn in /srv/conda/envs/notebook/lib/python3.7/site-packages (from sklearn) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.1.0)
Requirement already satisfied: numpy>=1.14.6 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.18.5)
Requirement already satisfied: scipy>=1.1.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from scikit-learn->sklearn) (1.4.1)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sklearn import linear_model

In [21]:
df.columns

Index(['folio', 'intp', 'entidad', 'desc_ent', 'sexo', 'edad', 'meses', 'peso',
       'ropa', 'talla', 'emb', 'temb', 'cintura', 'cadera', 'sistol',
       'diastol', 'hpresion', 'tbrazo', 'htension', 'PrimaryLast', 'code_upm',
       'est_dis', 'est_urb', 'est_marg', 'pondef', 'est_var'],
      dtype='object')

In [37]:
modelA = sm.OLS.from_formula('diastol ~ sistol ', data = df)
resultA = modelA.fit()
resultA.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                diastol   R-squared:                       0.441
Model:                            OLS   Adj. R-squared:                  0.441
Method:                 Least Squares   F-statistic:                 1.469e+04
Date:                Wed, 01 Dec 2021   Prob (F-statistic):               0.00
Time:                        18:39:01   Log-Likelihood:                -66351.
No. Observations:               18640   AIC:                         1.327e+05
Df Residuals:                   18638   BIC:                         1.327e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     23.6843      0.432     54.811      0.000      22.837      24.531
sistol         0.4375      0.004    121.220      0.000       0.430       0.445
==============================================================================
Omnibus:                     1040.446   Durbin-Watson:                   1.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4079.429
Skew:                           0.118   Prob(JB):                         0.00
Kurtosis:                       5.280   Cond. No.                         830.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
var = resultA.resid
var.median()

-0.0021017816189328187

In [24]:
df.iloc[:,13:]

,cadera,sistol,diastol,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,106.0,63.25,53.25,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,75.0,70.00,50.00,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,94.3,70.50,41.00,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,72.2,71.00,64.00,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,127.0,72.00,53.50,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18635,113.0,221.00,95.50,18:00,1,18:05,1,R3002,5,3,1,7615.607749,305
18636,113.7,222.25,78.00,18:40,1,18:40,1,M0408,5,3,1,195.314670,45
18637,86.0,230.00,66.00,8:00,3,23:00,1,M3024,2,1,2,1758.912979,302
18638,94.8,235.00,100.00,6:02,3,6:02,1,M2512,3,2,1,2354.581350,253
18639,120.0,240.00,150.00,13:50,3,13:00,1,M0143,2,1,2,591.847039,12

In [25]:
modelB = sm.OLS.from_formula('cadera ~ peso', data = df)
resultB = modelB.fit()
resultB.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 cadera   R-squared:                       0.604
Model:                            OLS   Adj. R-squared:                  0.604
Method:                 Least Squares   F-statistic:                 2.748e+04
Date:                Wed, 01 Dec 2021   Prob (F-statistic):               0.00
Time:                        18:34:30   Log-Likelihood:                -65165.
No. Observations:               18032   AIC:                         1.303e+05
Df Residuals:                   18030   BIC:                         1.304e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     57.4600      0.252    228.032      0.000      56.966      57.954
peso           0.6227      0.004    165.771      0.000       0.615       0.630
==============================================================================
Omnibus:                    22321.754   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6875856.023
Skew:                           6.463   Prob(JB):                         0.00
Kurtosis:                      97.786   Cond. No.                         253.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [26]:
df.columns

Index(['folio', 'intp', 'entidad', 'desc_ent', 'sexo', 'edad', 'meses', 'peso',
       'ropa', 'talla', 'emb', 'temb', 'cintura', 'cadera', 'sistol',
       'diastol', 'hpresion', 'tbrazo', 'htension', 'PrimaryLast', 'code_upm',
       'est_dis', 'est_urb', 'est_marg', 'pondef', 'est_var'],
      dtype='object')

In [27]:
new = df.loc[:,['sistol','diastol']]
new.head()

   sistol  diastol
0   63.25    53.25
1   70.00    50.00
2   70.50    41.00
3   71.00    64.00
4   72.00    53.50

In [28]:
df.corr()

,folio,intp,entidad,sexo,edad,meses,peso,ropa,talla,cintura,cadera,sistol,diastol,PrimaryLast,est_dis,est_urb,est_marg,pondef,est_var
folio,1.000000,-0.017127,0.999979,0.010344,0.026894,0.014225,-0.044368,0.011953,-0.071853,-0.026543,-0.032166,0.003985,-0.018598,NaN,-0.094484,-0.107161,0.002257,0.010347,0.999845
intp,-0.017127,1.000000,-0.017200,0.046257,-0.636936,-0.006015,-0.374168,-0.007191,-0.144495,-0.421887,-0.321075,-0.340492,-0.278265,NaN,-0.006402,-0.000918,0.016604,0.042477,-0.017334
entidad,0.999979,-0.017200,1.000000,0.010380,0.027015,0.014288,-0.044406,0.011915,-0.071862,-0.026583,-0.032198,0.004068,-0.018564,NaN,-0.094805,-0.107293,0.001842,0.010179,0.999861
sexo,0.010344,0.046257,0.010380,1.000000,0.039906,-0.000934,-0.124461,-0.001227,-0.463303,0.014791,0.169966,-0.083550,-0.057971,NaN,0.002736,0.007622,-0.014616,-0.041621,0.010459
edad,0.026894,-0.636936,0.027015,0.039906,1.000000,0.003416,0.317050,0.018021,0.021070,0.478879,0.340062,0.535218,0.345657,NaN,-0.035563,-0.019963,-0.027559,0.037230,0.026532
meses,0.014225,-0.006015,0.014288,-0.000934,0.003416,1.000000,-0.004255,0.003584,0.008326,0.000214,0.000300,0.009473,-0.004480,NaN,0.001648,0.000554,-0.001311,0.015791,0.014309
peso,-0.044368,-0.374168,-0.044406,-0.124461,0.317050,-0.004255,1.000000,0.006378,0.556587,0.791677,0.777061,0.353440,0.358054,NaN,0.087096,0.112852,-0.106389,0.085659,-0.042902
ropa,0.011953,-0.007191,0.011915,-0.001227,0.018021,0.003584,0.006378,1.000000,-0.005135,0.007701,0.003628,0.055130,-0.012078,NaN,-0.024589,-0.037460,0.015826,-0.050711,0.011431
talla,-0.071853,-0.144495,-0.071862,-0.463303,0.021070,0.008326,0.556587,-0.005135,1.000000,0.245208,0.273173,0.142837,0.152398,NaN,0.085241,0.109504,-0.096508,0.097229,-0.070432
cintura,-0.026543,-0.421887,-0.026583,0.014791,0.478879,0.000214,0.791677,0.007701,0.245208,1.000000,0.863396,0.403265,0.362961,NaN,0.049018,0.071307,-0.067250,0.062563,-0.025732
cadera,-0.032166,-0.321075,-0.032198,0.169966,0.340062,0.000300,0.777061,0.003628,0.273173,0.863396,1.000000,0.307012,0.296613,NaN,0.072143,0.103383,-0.099546,0.065710,-0.030944
sistol,0.003985,-0.340492,0.004068,-0.083550,0.535218,0.009473,0.353440,0.055130,0.142837,0.403265,0.307012,1.000000,0.663961,NaN,-0.013664,-0.012750,-0.014379,0.014744,0.003898
diastol,-0.018598,-0.278265,-0.018564,-0.057971,0.345657,-0.004480,0.358054,-0.012078,0.152398,0.362961,0.296613,0.663961,1.000000,NaN,0.020553,0.028117,-0.021853,0.034317,-0.018166
PrimaryLast,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
est_dis,-0.094484,-0.006402,-0.094805,0.002736,-0.035563,0.001648,0.087096,-0.024589,0.085241,0.049018,0.072143,-0.013664,0.020553,NaN,1.000000,0.865379,-0.231419,0.127373,-0.078457
est_urb,-0.107161,-0.000918,-0.107293,0.007622,-0.019963,0.000554,0.112852,-0.037460,0.109504,0.071307,0.103383,-0.012750,0.028117,NaN,0.865379,1.000000,-0.466739,0.247599,-0.092228
est_marg,0.002257,0.016604,0.001842,-0.014616,-0.027559,-0.001311,-0.106389,0.015826,-0.096508,-0.067250,-0.099546,-0.014379,-0.021853,NaN,-0.231419,-0.466739,1.000000,-0.291340,-0.002377
pondef,0.010347,0.042477,0.010179,-0.041621,0.037230,0.015791,0.085659,-0.050711,0.097229,0.062563,0.065710,0.014744,0.034317,NaN,0.127373,0.247599,-0.291340,1.000000,0.012575
est_var,0.999845,-0.017334,0.999861,0.010459,0.026532,0.014309,-0.042902,0.011431,-0.070432,-0.025732,-0.030944,0.003898,-0.018166,NaN,-0.078457,-0.092228,-0.002377,0.012575,1.000000

In [29]:
new.corr()

           sistol   diastol
sistol   1.000000  0.663961
diastol  0.663961  1.000000

In [75]:
modelC = sm.OLS.from_formula('diastol ~ sistol ', data = df)
resultC = modelC.fit()
resultC.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                diastol   R-squared:                       0.441
Model:                            OLS   Adj. R-squared:                  0.441
Method:                 Least Squares   F-statistic:                 1.469e+04
Date:                Wed, 01 Dec 2021   Prob (F-statistic):               0.00
Time:                        19:17:59   Log-Likelihood:                -66351.
No. Observations:               18640   AIC:                         1.327e+05
Df Residuals:                   18638   BIC:                         1.327e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     23.6843      0.432     54.811      0.000      22.837      24.531
sistol         0.4375      0.004    121.220      0.000       0.430       0.445
==============================================================================
Omnibus:                     1040.446   Durbin-Watson:                   1.746
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4079.429
Skew:                           0.118   Prob(JB):                         0.00
Kurtosis:                       5.280   Cond. No.                         830.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [76]:
z = resultC.resid
z.median()

0.002305549055435563